#!/usr/bin/env bash

record() {
  pactl list short sources | grep "bluez" && input="bluez_input.EC:66:D1:CC:8F:2F" || input="alsa_input.pci-0000_00_1f.3.analog-stereo"

  ffmpeg -f pulse -i $input -af "afftdn=nf=-75" "$HOME/Videos/audio/audio_$(date '+%a__%b%d__%H_%M_%S').wav" &
  echo $! > /tmp/audpid

  echo " " > /tmp/micicon && pkill -RTMIN+1 dwmblocks

  notify-send -t 1000 -h string:bgcolor:#a3be8c "Mic unmuted"
}

end() {
  kill -15 "$(cat /tmp/audpid)"
  rm -f /tmp/audpid

  echo " " > /tmp/micicon && pkill -RTMIN+1 dwmblocks

  notify-send -t 1000 -h string:bgcolor:#bf616a "Mic muted"
}

([[ -f /tmp/audpid ]] && end && exit 0) || record
