#!/usr/bin/env bash

record() {
  pactl list short sources | grep "bluez" && query=$(pactl list short sources | grep "bluez_input") || query=$(pactl list short sources | grep "alsa_input")

  trim=${query#*	}
  monitor=${trim%%	*} 

  ffmpeg -f pulse -i $monitor -af "afftdn=nf=-75" "$HOME/Videos/audio/audio_$(date '+%a__%b%d__%H_%M_%S').wav" &
  echo $! > /tmp/audpid

  echo " " > /tmp/micicon && pkill -RTMIN+1 dwmblocks

  notify-send -t 1000 -h string:bgcolor:#a3be8c "Mic unmuted"
}

end() {
  kill -15 "$(cat /tmp/audpid)"
  rm -f /tmp/audpid

  echo " " > /tmp/micicon && pkill -RTMIN+1 dwmblocks

  notify-send -t 1000 -h string:bgcolor:#bf616a "Mic muted"
}

([[ -f /tmp/audpid ]] && end && exit 0) || record
