#!/usr/bin/env bash

#script for recording via kmsgrab, read the README for more detail

export PULSE_SERVER="unix:/run/user/$(id -u)/pulse/native"

record() {
  [[ -f /tmp/winpid ]] && exit 1

  notify-send -t 1000 -h string:bgcolor:#a3be8c "Recording started" && sleep 1
  killall dunst

  pactl list short sources | grep "bluez" && input="bluez_output.EC:66:D1:CC:8F:2F.monitor" || input="alsa_output.pci-0000_00_1f.3.analog-stereo.monitor"

  sudo ffmpeg -device /dev/dri/card1 -f kmsgrab -r 60 -probesize 42M -i - -f pulse -i $input -ac 2 -vf 'hwmap=derive_device=vaapi,scale_vaapi=w=1920:h=1080:format=nv12' -c:v h264_vaapi -qp 15 -preset veryslow "$HOME/Videos/recording_$(date '+%a__%b%d__%H_%M_%S').mkv" &
  echo $! > /tmp/recpid

  ([[ -f /tmp/autorecpid ]] && echo " 󰑊 " > /tmp/recordingicon || echo "  " > /tmp/recordingicon) && pkill -RTMIN+1 dwmblocks
}

end() {
  kill -15 "$(cat /tmp/recpid)"
  rm -f /tmp/recpid

  ([[ -f /tmp/autorecpid ]] && echo "  " > /tmp/recordingicon || echo "  " > /tmp/recordingicon) && pkill -RTMIN+1 dwmblocks

  sleep 0.5 && dunst &
  notify-send -t 1000 -h string:bgcolor:#bf616a "Recording ended"
}

([[ -f /tmp/recpid ]] && end && exit 0) || record
