#!/usr/bin/env bash

static="omori48ShadowsHotspotStatic"
animated="omori48ShadowsHotspot"

record() {
  [[ -f /tmp/winpid ]] && exit 1

  notify-send -t 1000 -h string:bgcolor:#a3be8c "Recording started" && sleep 0.5
  killall dunst

  sed -i 's|Gtk/CursorThemeName.*|Gtk/CursorThemeName '\"$static\"'|' ~/.xsettingsd && killall -HUP xsettingsd
  plasma-apply-cursortheme $static --size 48

  pactl list short sources | grep "bluez" && query=$(pactl list short sources | grep "bluez_output") || query=$(pactl list short sources | grep "alsa_output")

  trim=${query#*	}
  monitor=${trim%%	*} 

  ffmpeg -init_hw_device vaapi=foo:/dev/dri/renderD128 -filter_hw_device foo -s "$(xdpyinfo | awk '/dimensions/{print $2}')" -f x11grab -r 60 -fpsprobesize 0 -i :0.0 -f pulse -i $monitor -ac 2 -vf 'format=nv12,hwupload' -c:v hevc_vaapi -qp 25 -rc_mode CQP "$HOME/Videos/recording_$(date '+%a__%b%d__%H_%M_%S').mkv" &
  echo $! > /tmp/recpid

  ([[ -f /tmp/autorecpid ]] && echo " 󰑊 " > /tmp/recordingicon || echo "  " > /tmp/recordingicon) && pkill -RTMIN+1 dwmblocks
}

end() {
  kill -15 "$(cat /tmp/recpid)"
  rm -f /tmp/recpid

  ([[ -f /tmp/autorecpid ]] && echo "  " > /tmp/recordingicon || echo "  " > /tmp/recordingicon) && pkill -RTMIN+1 dwmblocks

  sleep 0.5 && dunst &
  notify-send -t 1000 -h string:bgcolor:#bf616a "Recording ended"

  sed -i 's|Gtk/CursorThemeName.*|Gtk/CursorThemeName '\"$animated\"'|' ~/.xsettingsd && killall -HUP xsettingsd
  plasma-apply-cursortheme $animated --size 48
}

([[ -f /tmp/recpid ]] && end && exit 0) || record
