#!/usr/bin/env bash

record() {
  [[ -f /tmp/winpid ]] && exit 1

  notify-send -t 1000 -h string:bgcolor:#a3be8c "Recording started" && sleep 0.5
  killall dunst

  pactl list short sources | grep "bluez" && query=$(pactl list short sources | grep "bluez_output") || query=$(pactl list short sources | grep "alsa_output")

  trim=${query#*	}
  monitor=${trim%%	*} 

  ffmpeg -init_hw_device vaapi=va:/dev/dri/renderD128 -filter_hw_device va -s "$(xdpyinfo | awk '/dimensions/{print $2}')" -f x11grab -r 60 -probesize 42M -i :0.0 -f pulse -i $monitor -ac 2 -vf 'format=nv12,hwupload' -c:v h264_vaapi -qp 15 -preset veryslow "$HOME/Videos/recording_$(date '+%a__%b%d__%H_%M_%S').mkv" &
  echo $! > /tmp/recpid

  ([[ -f /tmp/autorecpid ]] && echo " 󰑊 " > /tmp/recordingicon || echo "  " > /tmp/recordingicon) && pkill -RTMIN+1 dwmblocks
}

end() {
  kill -15 "$(cat /tmp/recpid)"
  rm -f /tmp/recpid

  ([[ -f /tmp/autorecpid ]] && echo "  " > /tmp/recordingicon || echo "  " > /tmp/recordingicon) && pkill -RTMIN+1 dwmblocks

  sleep 0.5 && dunst &
  notify-send -t 1000 -h string:bgcolor:#bf616a "Recording ended"
}

([[ -f /tmp/recpid ]] && end && exit 0) || record
