#!/usr/bin/env bash

static="omori48ShadowsHotspotStatic"
animated="omori48ShadowsHotspot"

record() {
  [[ -f /tmp/autorecpid || -f /tmp/recpid ]] && exit 1

  notify-send -t 1000 -h string:bgcolor:#a3be8c "Recording current window"

  sed -i 's|Gtk/CursorThemeName.*|Gtk/CursorThemeName '\"$static\"'|' ~/.xsettingsd && killall -HUP xsettingsd
  plasma-apply-cursortheme $static --size 48

  query=$(xwininfo -id $(xdotool getactivewindow) | grep "Window id")
  info=${query%% \"*}
  id=${info##*: }
  echo $id > /tmp/winid1

  pactl list short sources | grep "bluez" && query=$(pactl list short sources | grep "bluez_output") || query=$(pactl list short sources | grep "alsa_output")

  trim=${query#*	}
  monitor=${trim%%	*}

  ffmpeg -init_hw_device vaapi=va:/dev/dri/renderD128 -filter_hw_device va -f x11grab -window_id $id -r 60 -probesize 42M -i :0.0 -f pulse -i $monitor -ac 2 -vf 'format=nv12,hwupload' -c:v h264_vaapi -qp 19 -preset veryslow "$HOME/Videos/tmp/recording_$(date '+%a__%b%d__%H_%M_%S').mkv" &
  echo $! > /tmp/winpid

  echo "  " > /tmp/recordingicon && pkill -RTMIN+1 dwmblocks
}

end() {
  kill -15 "$(cat /tmp/winpid)"
  rm -f /tmp/winpid

  query=$(xwininfo -id $(xdotool getactivewindow) | grep "Window id")
  info=${query%% \"*}
  id=${info##*: }
  echo $id > /tmp/winid2

  if [[ $(cat /tmp/winid1) == $(cat /tmp/winid2) ]]; then
    rm -f /tmp/winid1 && rm -f /tmp/winid2
    echo "  " > /tmp/recordingicon && pkill -RTMIN+1 dwmblocks

    notify-send -t 3000 -h string:bgcolor:#D29654 "Merging videos"

    sed -i 's|Gtk/CursorThemeName.*|Gtk/CursorThemeName '\"$animated\"'|' ~/.xsettingsd && killall -HUP xsettingsd
    plasma-apply-cursortheme $animated --size 48

    for filename in $HOME/Videos/tmp/*.mkv; do
      echo "file $filename" >> concat-list
    done
    ffmpeg -f concat -safe 0 -i concat-list $HOME/Videos/recording_$(date '+%a__%b%d__%H_%M_%S').mkv
    rm -rf $HOME/Videos/tmp/*
    rm -f concat-list

    notify-send -t 1000 -h string:bgcolor:#bf616a "Merging ended"
  else
    record &
  fi
}

([[ -f /tmp/winpid ]] && end && exit 0) || record
