#!/usr/bin/bash

pidof -qx "betterlockscreen" && exit

if !(pidof -qx "rofi"); then
    xidlehook --socket /tmp/socket --timer 0 'brightnessctl s 5%' 'brightnessctl s 15% && xidlehook-client --socket /tmp/socket control --timer 0 --action disable' &
    pid1=$!
    sleep 15 && kill -9 $pid1
    [[ $(brightnessctl g) == "14400" ]] && exit || (xset dpms force off && brightnessctl s 15%)
    sleep 15
    [[ -n $(xset -q | grep "Monitor is On") ]] && xset s off -dpms && exit
fi

xidlehook --timer 15 'xset dpms force off' '' --timer 3585 'systemctl suspend' '' &
pid2=$!

trap "kill -9 $pid2; xset s off -dpms" EXIT

sleep 0.5 &&
killall rofi & 
betterlockscreen -l
