#!/bin/bash

MODE="/tmp/rofi-mode"
KILLED="/tmp/rofi-killed"
SWITCHED="/tmp/rofi-switched"

[[ -z $(cat $KILLED) ]] && echo "true" > "$KILLED"
[[ -z $(cat $SWITCHED) ]] && echo "false" > "$SWITCHED"
[[ -z $(cat $MODE) ]] && echo 0 > "$MODE"
[[ $(cat $KILLED) == "true" ]] && echo 0 > "$MODE"
echo "false" > "$KILLED"

theme='omori2'

if [[ $(cat $SWITCHED) == "false" ]]; then
    echo "true" > "$SWITCHED"
    killall rofi

    case $(cat $MODE) in
        0)
            ## Run
            rofi \
                -show run -show-emojis NULL \
                -theme ${dir}/${theme}.rasi &
            ;;
        1)
            ## Run
            rofi \
                -show window -show-emojis NULL \
                -theme ${dir}/${theme}.rasi &
            ;;
        2)
            ## Run
            rofi \
                -show drun -show-emojis NULL \
                -theme ${dir}/${theme}.rasi &
            ;;
    esac
fi

case $(cat $MODE) in
    0) echo 1 > "$MODE" ;;
    1) echo 2 > "$MODE" ;;
    2) echo 0 > "$MODE" ;;
esac

trap "clip" EXIT
