#!usr/bin/bash

MODE="/tmp/rofi-mode"
SWITCHED="/tmp/rofi-switched"

theme='omori1';

if [[ $(cat $SWITCHED) == "true" ]]; then
    echo "false" > "$SWITCHED"
    killall rofi;

    if [[ $(cat $MODE) == "0" ]]; then
        ## Run
        rofi \
            -show drun -show-emojis NULL \
            -theme ${dir}/${theme}.rasi &
    elif [[ $(cat $MODE) == "1" ]]; then
        ## Run
        rofi \
            -show run -show-emojis NULL \
            -theme ${dir}/${theme}.rasi &
    elif [[ $(cat $MODE) == "2" ]]; then
        ## Run
        rofi \
            -show window -show-emojis NULL \
            -theme ${dir}/${theme}.rasi &
    fi
    sleep 0.1
    xdotool key ctrl+p;
fi
